name: Deployment

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy
      - run: sudo apt-get install opencl-c-headers
      - run: make target=joinc platform=
